plugins: 
- jekyll-seo-tag
  
 
  
  title: Pushpinder Singh Grewal's portfolio

description: Portfolio of pushpinder Singh Grewal

url: http://pushpindersinghgrewal.tk

author: Pushpinder Singh Grewal

author_email: pndrgrewal12@gmail.com

twitter:
  username: pndrgrewal
facebook: pndrgrewal
